config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :workspaces do
    resources :reviews, only: [:create, :destroy]
  end

  root to: "pages#welcome"
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :workspace
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :workspaces
  has_many :reviews
end

app/models/workspace.rb
class Workspace < ActiveRecord::Base
  belongs_to :user
  has_many :reviews

  def average_rating
    if reviews.blank?
      0
    else
      reviews.average(:star).round(2)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :remember_me) }
  devise_parameter_sanitizer.for(:sign_in) {|u| u.permit(:name, :email, :password, :remember_me) }
  devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :remember_me, :current_password) }
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome

  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.create(review_params)
    workspace = @review.workspace

    redirect_to workspace
  end

  def destroy
    @review = Review.find(params[:id])
    workspace = @review.workspace
    @review.destroy

    redirect_to workspace
  end

  private
  def review_params
    params.require(:review).permit(:star, :comment, :workspace_id, :user_id)
  end
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    # workspaces sorted by top rating

  @category = params[:category]
  @location = params[:location]

  @workspaces = Workspace

  if @category
    @workspaces = @workspaces.where(category: @category)
  end

  if @location
    @workspaces = @workspaces.where("address like '%#{@location}%'")
  end

  if @workspaces == Workspace
    @workspaces = Workspace.all
  end

  @workspaces = @workspaces.sort_by { |w| w.average_rating }.reverse

    # workspaces sorted by category
  # @workspaces = Workspace.all.sort_by { |w| w.category }

  # @search = Workspace.new(params[:workspace])
  # @workspaces = Workspace.address[@search.address]

  end

  def new
    @workspace = current_user.workspaces.build
  end

  def create
    @workspace = current_user.workspaces.build(workspace_params)

    if @workspace.save
      redirect_to @workspace
    else
      render 'new'
    end
  end

  def show
    @workspace = Workspace.find(params[:id])

    @review = Review.new
    @reviews = @workspace.reviews

    # check to see if user has left a review
    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def edit

  end

  def update
    if @workspace.update(workspace_params)
			redirect_to @workspace
		else
			render 'edit'
		end
  end

  def destroy

  end

  private
  def workspace_params
  params.require(:workspace).permit(:name, :address, :company_url, :category, :image_url, :hours, :wifi)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>WifinderApp</title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'raty.js', 'data-turbolinks-track' => false %>
 <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
</head>
<body>

  <header>
   <div class="navbar">
       <ul>
         <li><%= link_to (image_tag "wifinder_white.png"), root_path %></li>
         <li><%= link_to "All Workspaces", workspaces_path %></li> ||
         <% if !current_user %>
           <li><%= link_to "Sign Up", new_user_registration_path %></li> ||
           <li><%= link_to "Sign In", new_user_session_path %></li> ||
         <% else %>
           <li><%= link_to "Add New Workspace", new_workspace_path %></li> ||
           <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
         <% end %>

       </ul>
     </div>
   </div>
  </header>
<div class="page-wrap">

  <div class="msg">
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

</div>

  <div class="container">
   <%= yield %>
  </div>

</div>
<footer class="site-footer">

 <div class="footer">
   <div class="meow">-</div>

      <div class="footer">
        <ul>
          <li>About&nbsp;</li>||
          <li>Contact&nbsp;</li>||
          <li>Careers</li>
          <%= image_tag "signal.png", id: "signal" %>
        </ul>
      </div>
 </div>

</footer>


</body>
</html>

app/views/pages/welcome.html.erb
<!-- <h1>Welcome to WiFinder</h1> -->
<div class="firstpage">
<%= image_tag "wifinder_white.png", class: "welcomelogo" %>
</div>

<p class="tagline">Find and rank great public workspaces with wifi availability</p>
<p class="starterlink"><%= link_to "FIND WORKSPACES", workspaces_path %> </p>

<div id="bg">
<%= image_tag "bag_and_hands.jpg" %>
</div>

app/views/reviews/_form.html.erb
<%= form_for [@workspace, @review] do |f| %>
  <div id="user_stars"></div>
  <%= f.text_field :comment, placeholder: "comment here" %>

  <%= f.hidden_field :workspace_id, value: @workspace.id %>
  <%= f.hidden_field :user_id, value: current_user.id %><br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#user_stars').raty({
    path: '/assets',
    scoreName: 'review[star]',
    score: 1
  });
</script>

app/views/reviews/_index.html.erb
<% if @reviews.blank? %>
  <span>There are no reviews yet. Be the first!</span>
<% end %>

<% @reviews.order("id desc").each do |review| %>
  <div class="review-user">
      <span>About <%= time_ago_in_words(review.created_at) %> ago,</span>
      <span><%= review.user.name %> said:</span>
  </div>
  <div class="stars_<%= review.id %>">
  </div>
  <div class="review-comment">"<%= review.comment %>"</div>
  <div class="remove-review">
    <% if current_user && current_user.id == review.user.id %>
      <%= link_to "Remove", [@workspace, review], method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
  </div>

  <script>
    $('#stars_<%= review.id %>').raty({
      path: '/assets',
      readOnly: true,
      score: <%= review.star %>
    })
  </script>

<% end %>

app/views/workspaces/_form.html.erb
<div id="form">

  <%= form_for @workspace do |f| %>
    <%= f.label :category %><br>
    <%= f.select :category do %>
      <%= ["Coffee Shop", "Library", "Cafe", "Academic Commons"]. each do |category| %>
        <%= content_tag(:option, category, value: category) %>
        <% end %>
    <% end %><br>

    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.label :address %><br>
    <%= f.text_field :address %><br>


    <%= f.label :company_url %><br>
    <%= f.text_field :company_url %><br>

    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %><br>

    <%= f.label :hours %><br>
    <%= f.text_field :hours %><br>

    <%= f.label "How's the Wifi?"%><br>
    <%= f.text_field :wifi%><br>


    <%= f.submit %>

  <% end %>


</div>

app/views/workspaces/index.html.erb
<div id="workspace_index"  data-no-turbolink>
<h1>All Workspaces with Free WiFi (By Top Rating)</h1>
<span><%= link_to "All ||", workspaces_path %></span>

<% ["Coffee Shop", "||", "Library", "||", "Cafe", "||", "Academic Commons"].each do |category| %>
  <span><%= link_to category, workspaces_path(category: category) %></span>
<% end %>

<%#= form_for(@search, :name => { :action => "index" }, :html => {:method => :get} ) do |f| %> <%#= f.text_field(:address) %>

<%= form_tag(workspaces_path, method: 'get') do %>
  <%= text_field_tag :location, "Search by Location" %>
  <%= submit_tag :search %>
<% end %>

<ul>
  <div class="cushion column-4">&nbsp;</div>

    <div class="cushion column-4">
      <% @workspaces.each do |workspace| %>
        <div class="workspaces row">
          <li class="workspaceimg">
            <%= image_tag workspace.image_url, class: "column-5" %>
          </li>
          <li class="workspaceinfo column-5">
            <p><%= link_to workspace.name, workspace %></p>
            <p>Rating: <%= workspace.average_rating %></p>
            <p><%= workspace.address %></p>
            <p><%= workspace.category %></p>
            <p><%= link_to "Website", workspace.company_url%></p>
            <p><%= workspace.hours %></p>
          </li>
          <li class="column-2">&nbsp;</li>
        </div>
      <% end %>
    </div>
  <div class="cushion column-4">&nbsp;</div>
</ul>

</div>

app/views/workspaces/new.html.erb
<h1>Add a new Workspace</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/workspaces/show.html.erb
<div  data-no-turbolink>
  <h1 class="showtitle"><%= @workspace.name %></h1>

<div class="ratings">
  <% if !@reviews.blank? %>
    <h2>Average Rating: </h2>
    <p><span id="average_rating"></span> (<%= @reviews.count %> <%= @reviews.count != 1 ? "Reviews" : "Review" %>)</p>
  <% end %>
</div>

  <ul>
      <%= image_tag @workspace.image_url, class: "showimg" %>
      <li><%= link_to @workspace.name, @workspace %></li>
      <li><%= @workspace.address %></li>
      <li><%= @workspace.category %></li>
      <li><%= link_to "Workspace website", @workspace.company_url %></li>
      <li><%= @workspace.hours %></li>
  </ul>

    <div id="map-container" data-no-turbolink>
      <div id="map-canvas"></div>
    </div>
  <script src="https://maps.googleapis.com/maps/api/js"></script>
  <script>
    function initialize() {
      var mapCanvas = document.getElementById('map-canvas');
      var mapOptions = {
        center: new google.maps.LatLng(38.904854, -77.03394000000003),
        zoom: 15,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      }
      var map = new google.maps.Map(mapCanvas, mapOptions);
      var marker = new google.maps.Marker({
      	position: new google.maps.LatLng(38.904854, -77.03394000000003),
      	title: "Learning at GA!"
      });
      marker.setMap(map);
    }
    google.maps.event.addDomListener(window, 'load', initialize);
  </script>

    <div class="reviews-header">
      <h3>Reviews</h3>
    </div>
    <div class="reviews-list">
      <%= render "reviews/index" %>
    </div>
    <div class="reviews-new">
      <% if !@hasReview && current_user %>
        <%= render "reviews/form" %>
      <% elsif !current_user %>
        <p>
          Please log in to leave a review!
        </p>
      <% end %>
    </div>

</div>

<script>
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%= @workspace.average_rating %>
  })
</script>